export default {
    "carrier" : {id: "carrier", numberOfDice: 1, target: 9, name: "Carrier"},
    "cruiser": {id: "cruiser", numberOfDice: 1, target: 7, name: "Cruiser"},
    "dreadnought": {id: "dreadnought", numberOfDice: 1, target: 5, name: "Dreadnought"},
    "destroyer": {id: "destroyer", numberOfDice: 1, target: 9, name: "Destroyer"},
    "fighter": {id: "fighter", numberOfDice: 1, target: 9, name: "Fighter"},
    "warsun": {id: "warsun", numberOfDice: 3, target: 3, name: "War Sun"},
    "flagship_arborec": {id: "flagship_arborec", numberOfDice: 2, target: 7, name: "Arborec Flagship"},
    "flagship_creuss": {id: "flagship_creuss", numberOfDice: 1, target: 5, name: "Creuss Flagship"},
    "flagship_hacan": {id: "flagship_hacan", numberOfDice: 2, target: 7, name: "Hacan Flagship"},
    "flagship_jol": {id: "flagship_jol", numberOfDice: 2, target: 5, name: "Jol Flagship"},
    "flagship_letnev": {id: "flagship_letnev", numberOfDice: 2, target: 5, name: "Letnev Flagship"},
    "flagship_liz": {id: "flagship_liz", numberOfDice: 2, target: 5, name: "Liz Flagship"},
    "flagship_mentak": {id: "flagship_mentak", numberOfDice: 2, target: 7, name: "Mentak Flagship"},
    "flagship_muaat": {id: "flagship_muaat", numberOfDice: 3, target: 3, name: "Muaat Flagship"},
    "flagship_naalu": {id: "flagship_naalu", numberOfDice: 2, target: 9, name: "Naalu Flagship"},
    "flagship_nekro": {id: "flagship_nekro", numberOfDice: 2, target: 9, name: "Nekro Flagship"},
    "flagship_saar": {id: "flagship_saar", numberOfDice: 2, target: 5, name: "Saar Flagship"},
    "flagship_sardakk": {id: "flagship_sardakk", numberOfDice: 2, target: 6, name: "Sardakk Flagship"},
    "flagship_sol": {id: "flagship_sol", numberOfDice: 2, target: 5, name: "Sol Flagship"},
    "flagship_winnu": {id: "flagship_winnu", numberOfDice: 0, target: 7, name: "Winnu Flagship"},
    "flagship_xxcha": {id: "flagship_xxcha", numberOfDice: 2, target: 7, name: "Xxcha Flagship"},
    "flagship_yin": {id: "flagship_yin", numberOfDice: 2, target: 9, name: "Yin Flagship"},
    "flagship_yssaril": {id: "flagship_yssaril", numberOfDice: 2, target: 5, name: "Yssaril Flagship"}
}