export default {
    "carrier" : {name: "carrier", numberOfDice: 1, target: 9, friendlyName: "Carrier"},
    "cruiser": {name: "cruiser", numberOfDice: 1, target: 7, friendlyName: "Cruiser"},
    "dreadnought": {name: "dreadnought", numberOfDice: 1, target: 5, friendlyName: "Dreadnought"},
    "destroyer": {name: "destroyer", numberOfDice: 1, target: 9, friendlyName: "Destroyer"},
    "fighter": {name: "fighter", numberOfDice: 1, target: 9, friendlyName: "Fighter"},
    "warsun": {name: "warsun", numberOfDice: 3, target: 3, friendlyName: "War Sun"},
    "flagship_arborec": {name: "flagship_arborec", numberOfDice: 2, target: 7, friendlyName: "Arborec Flagship"},
    "flagship_creuss": {name: "flagship_creuss", numberOfDice: 1, target: 5, friendlyName: "Creuss Flagship"},
    "flagship_hacan": {name: "flagship_hacan", numberOfDice: 2, target: 7, friendlyName: "Hacan Flagship"},
    "flagship_jol": {name: "flagship_jol", numberOfDice: 2, target: 5, friendlyName: "Jol Flagship"},
    "flagship_letnev": {name: "flagship_letnev", numberOfDice: 2, target: 5, friendlyName: "Letnev Flagship"},
    "flagship_liz": {name: "flagship_liz", numberOfDice: 2, target: 5, friendlyName: "Liz Flagship"},
    "flagship_mentak": {name: "flagship_mentak", numberOfDice: 2, target: 7, friendlyName: "Mentak Flagship"},
    "flagship_muaat": {name: "flagship_muaat", numberOfDice: 3, target: 3, friendlyName: "Muaat Flagship"},
    "flagship_naalu": {name: "flagship_naalu", numberOfDice: 2, target: 9, friendlyName: "Naalu Flagship"},
    "flagship_nekro": {name: "flagship_nekro", numberOfDice: 2, target: 9, friendlyName: "Nekro Flagship"},
    "flagship_saar": {name: "flagship_saar", numberOfDice: 2, target: 5, friendlyName: "Saar Flagship"},
    "flagship_sardakk": {name: "flagship_sardakk", numberOfDice: 2, target: 6, friendlyName: "Sardakk Flagship"},
    "flagship_sol": {name: "flagship_sol", numberOfDice: 2, target: 5, friendlyName: "Sol Flagship"},
    "flagship_winnu": {name: "flagship_winnu", numberOfDice: 0, target: 7, friendlyName: "Winnu Flagship"},
    "flagship_xxcha": {name: "flagship_xxcha", numberOfDice: 2, target: 7, friendlyName: "Xxcha Flagship"},
    "flagship_yin": {name: "flagship_yin", numberOfDice: 2, target: 9, friendlyName: "Yin Flagship"},
    "flagship_yssaril": {name: "flagship_yssaril", numberOfDice: 2, target: 5, friendlyName: "Yssaril Flagship"}
}